// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmEedSM_jxHorQQ71P0EvUlG7z4jUP6UU',
    appId: '1:990952892848:web:4dc448d6c0be1eabc08e75',
    messagingSenderId: '990952892848',
    projectId: 'bano-qabil-student',
    authDomain: 'bano-qabil-student.firebaseapp.com',
    storageBucket: 'bano-qabil-student.firebasestorage.app',
    measurementId: 'G-PGN215WED3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqHTPFcSn2OYcXLeCID_kIekrOYDfcvg',
    appId: '1:990952892848:android:23e244e73906a408c08e75',
    messagingSenderId: '990952892848',
    projectId: 'bano-qabil-student',
    storageBucket: 'bano-qabil-student.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtn4QkN7nKHG65d3aEIR6TwPaTebjeBLE',
    appId: '1:990952892848:ios:5f8f48fdf9063da7c08e75',
    messagingSenderId: '990952892848',
    projectId: 'bano-qabil-student',
    storageBucket: 'bano-qabil-student.firebasestorage.app',
    iosBundleId: 'com.example.banoQabilStudent',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtn4QkN7nKHG65d3aEIR6TwPaTebjeBLE',
    appId: '1:990952892848:ios:5f8f48fdf9063da7c08e75',
    messagingSenderId: '990952892848',
    projectId: 'bano-qabil-student',
    storageBucket: 'bano-qabil-student.firebasestorage.app',
    iosBundleId: 'com.example.banoQabilStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmEedSM_jxHorQQ71P0EvUlG7z4jUP6UU',
    appId: '1:990952892848:web:5c1efc7a5eb52f58c08e75',
    messagingSenderId: '990952892848',
    projectId: 'bano-qabil-student',
    authDomain: 'bano-qabil-student.firebaseapp.com',
    storageBucket: 'bano-qabil-student.firebasestorage.app',
    measurementId: 'G-ZW3E9T911B',
  );
}
